#!/usr/bin/env ruby
# frozen_string_literal: true

require 'active_support'
require 'active_support/core_ext'

class VirtualHost
  attr_reader :path, :domains, :jcr_roots
  attr_writer :domains, :jcr_roots

  def initialize(path)
    @path = path
  end
end

MATCH_GROUP_REGEX = /\$\d.*$/i
PT_REGEX = /rewriterule \S+ (\S+) \[.*PT.*\]/i
VARIABLE_REGEX = /([A-Z_]+_WHITE_DOMAIN)
emcm_web_root = ARGV[0].to_s

rewrite_dir = File.join(emcm_web_root, 'dispatcher', 'src', 'conf.d', 'rewrites')
virtual_hosts_dir = File.join(emcm_web_root, 'dispatcher', 'src', 'conf.d', 'available_vhosts')
variables_dir = File.join(emcm_web_root, 'dispatcher', 'src', 'conf.d', 'variables')
# ~/work/digital/emcm-web/develop/dispatcher/src/conf.d/available_vhosts/aem_cxd_sales_publish.vhost
# ~/work/digital/emcm-web/develop/dispatcher/src/conf.d/variables/sales_legalsolutions_tr_com_universal.vars

def find_domain(variable, variables_dir)
  paths = Dir.entries(variables_dir)
    .select { |file| file =~ /\.vars$/ }
    .map(&:to_s)
    .reject(&:blank?)
end

def find_domains(virtual_host, virtual_hosts_dir, variables_dir)
  paths = Dir.entries(virtual_hosts_dir)
    .select { |file| file =~ /\.vhost$/ }
    .map(&:to_s)
    .reject(&:blank?)

  paths.each do |path|
    file_path = File.join(rewrite_dir, path)

    lines = File.readlines(path)
      .map(&:chomp)

    has_rewrite_file = lines
      .select { |line| line =~ /include\s#{virtual_host.path}/i }
      .any?

    next unless has_rewrite_file

    variables = lines
      .select { |line| line.match? VARIABLE_REGEX }
      .map { |line| line.match(VARIABLE_REGEX)[1] }
      .flatten

    next unless variables.empty?

    domains = variables.each do |variable|
      find_domain(variable)
    end

    domains
end

def find_jcr_roots(rewrite_dir)
  paths = Dir.entries(rewrite_dir)
    .select { |file| file =~ /\.rules$/ }
    .map(&:to_s)
    .reject(&:blank?)

  paths.each do |path|
    file_path = File.join(rewrite_dir, path)
    host = VirtualHost.new(file_path)

    lines = File.readlines(path)
      .map(&:chomp)

    results = lines
      .select { |line| line =~ PT_REGEX }
      .map { |line| line.match(PT_REGEX)[1] }
      .map(&:to_s)
      .map { |line| line.gsub('"', '') }
      .reject(&:blank?)
      .reject { |line| line.match?(/favicon\.ico$/) }
      .reject { |line| line.match?(/sitemap\.xml$/) }
      .reject { |line| line.match?(/robots\.txt$/) }
      .map { |line| line.gsub(MATCH_GROUP_REGEX, '') }
      .sort
      .uniq

    host.jcr_roots = results
    puts results.join("\n") unless results.empty?
  end
end

find_jcr_roots(rewrite_dir)
