#!/usr/bin/env bash

set +e;

if [[ -z $VERSION ]]; then
  echo "VERSION is missing"
  exit 1;
fi

TAG_NAME="release-${VERSION}"
UAT_BRANCH="adobe/uatdeploy"

NONE_RENDERED_FILES=$(git diff "${TAG_NAME}..${UAT_BRANCH}" --name-only | ag --invert-match '^dispatcher\/render')
git diff -B "${TAG_NAME}..${UAT_BRANCH}" -- ${NONE_RENDERED_FILES}
