#!/usr/bin/env bash

# First argument: RELEASE_VERSION

if [[ -z $RELEASE_VERSION ]]; then
  echo 'RELEASE_VERSION is not set';

  exit 1
fi

mvn versions:set-property \
    -Dproperty=revision \
    -DnewVersion="$RELEASE_VERSION"
