#!/usr/bin/env ruby
require 'active_support/all'

days = (Date.new(2017, 7, 20) - Date.today).to_i
if days > 1
  puts "#{days} days left"
elsif days == 1
  puts '1 day left'
else
  puts 'How was it?'
end
