#!/usr/bin/env ruby
# frozen_string_literal

require_relative '../lib/new_candidate'

class NewCandidateExe < Thor
  option :role, type: :string, required: true
  option :date, type: :string, required: true
  option :time, type: :string, required: true
  option :hacker_rank_url, type: :string, required: true
  option :wd5_url, type: :string, required: true
  option :additional_interviewers, type: :string
  option :team, type: :string, default: "Digital"
  option :resume, type: :string
  desc "Create a directory for a new candidate", "Create a directory for a new candidate. Warning this will rewrite the notes, the feedback, and the resume (if specified)"
  def create(name)
    puts "hello #{name}"
    puts options[:date]

    puts Notes
      .new(name, options[:role], options[:date], options[:time], options[:hacker_rank_url], options[:wd5_url], options[:additional_interviewers], options[:team])
      .render
  end
end

NewCandidateExe.start(ARGV)
