#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'rest-client'
require 'base64'

TOKEN = ENV['TOKEN']
ID = ENV['ID']
ORGANIZATION = 'tr-commercial-eng'
PROJECT = 'Commercial%20Engineering'
URL = "https://dev.azure.com/#{ORGANIZATION}/#{PROJECT}/_apis/wit/workitems/#{ID}?api-version=7.0".freeze

credentials = Base64.encode64(":#{TOKEN}").strip
credentials = credentials.gsub("\n", '')
headers = {
  'Authorization' => "Basic #{credentials}"
}
begin
  response = RestClient.get URL, headers

  return unless response.code == 200

  puts JSON.parse(response.body).to_json
rescue StandardError => e
  puts e
  puts e.class

  exit 1
end
