#!/usr/bin/env bash

ID=$1
ORGANIZATION='tr-commercial-eng'
PROJECT='Commercial%20Engineering'
URL="https://dev.azure.com/${ORGANIZATION}/${PROJECT}/_apis/wit/workitems/${ID}?api-version=7.0"

curl --user ":${TOKEN}" "${URL}" --silent | jsonlint
