#!/usr/bin/env bash

curl \
  -X POST \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token ${TOKEN}" \
  https://api.github.com/repos/tr/digital_emcm-web/actions/workflows/deploy_to_uat.yml/dispatches \
  -d "{ \
    \"ref\": \"release\", \
    \"inputs\": { \
      \"release_tag\": \"${RELEASE_TAG}\" \
    } \
  }"
