#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

values = IO.readlines('passwords.txt').map do |line|
  key, value = line.split(':')

  password = value.split(' ').join

  # puts "#{key}: #{password}"
  [key, password]
end.to_h

# require 'pry-byebug'
# binding.pry

puts JSON.generate(values)
