#!/usr/bin/env bash

curl \
  -X POST \
  -H "Accept: application/vnd.github.v3+json" \
  -H "Authorization: token ${TOKEN}" \
  https://api.github.com/repos/tr/digital_emcm-web/actions/workflows/new-sprint.yml/dispatches \
  -d "{ \
    \"ref\": \"ab-685552-test\"
  }"
