#!/usr/bin/env ruby
# frozen_string_literal: true

require 'active_support'
require 'active_support/duration'
require 'active_support/core_ext'

days = ARGV[0].to_i

result = DateTime.now + days.days

puts result.strftime('%A %d-%m-%Y')
