#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative './lib/git'

def branch_name
  return ARGV[0].strip if ARGV.size == 2

  Git.branch_name
end

def path
  return ARGV[1].strip if ARGV.size == 2

  ARGV[0].strip
end

def current_path
  path.delete_prefix(Dir.pwd)[1..-1]
end

def absolute_path?
  return path[0] == '/'
end

def file_url
  "#{Git.repo_url}/blob/#{branch_name}/#{current_path}"
end

puts file_url
