#!/usr/bin/env bash

echo "Are you sure? [Y/n]";
read answer

if [[ "${answer,,}" == 'y' || "${answer}" == '' ]]
then
    untracked_files=$(git ls-files -o --exclude-standard);

    rm -rf "$untracked_files";
fi
