#!/usr/bin/env ruby
# frozen_string_literal: true

def url
  `git config remote.origin.url`
    .strip
    .gsub(/^git@/, 'https://')
    .gsub(%r{\.com(?:\/|:)(.*)\/(.*)\.git$}, '.com/\1/\2')
end

if ARGV.size.positive?
  branch = ARGV[0];

  puts "#{url}/tree/#{branch}"

  return
end

puts url
