#!/usr/bin/env ruby
# frozen_string_literal: true

def branch_name
  return ARGV[0].strip if ARGV.size == 2

  `git rev-parse --abbrev-ref HEAD`.chomp
end

def path
  return ARGV[1].strip if ARGV.size == 2

  ARGV[0].strip
end

def file_url
  `git config remote.origin.url`
    .strip
    .gsub(/^git@/, 'https://')
    .gsub(%r{\.com(?:/|:)(.*)/(.*)(?:\.git)?$}, ".com/\\1/\\2/blob/#{branch_name}/#{path}")
end

puts file_url
