#!/usr/bin/env ruby
# frozen_string_literal: true

def pull_requests_url
  `git config remote.origin.url`
    .strip
    .gsub(/^git@/, 'https://')
    .gsub(%r{\.com:(.*)\/(.*)\.git$}, '.com/\1/\2/pulls')
end

puts pull_requests_url
