#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative './lib/git'

def branch_name
  return ARGV[0].strip if ARGV.size == 2

  Git.branch_name
end

def path
  specified_path = if ARGV.size == 2
    ARGV[1].strip
  else
    ARGV[0].strip
  end

  if specified_path[0] == '~'
    specified_path.gsub('~', ENV['HOME'])
  end

  specified_path
end

def relative_path
  p = path
  if absolute_path? p
    return p.delete_prefix(Dir.pwd)
  end

  p
end

def absolute_path?(path)
  return path[0] == '/'
end

def file_url
  "#{Git.repo_url}/blob/#{branch_name}#{relative_path}"
end

puts file_url
