#!/usr/bin/env ruby
# frozen_string_literal: true

# Update the projects' ctags file
class Ctags
  attr_reader :language
  def initialize(language = 'ruby')
    @language = language.to_s.strip
  end

  def update(paths)
    paths = Array(paths).map(&:strip).join(' ')

    `ctags -R --languages=#{language} --exclude=.git --exclude=log #{paths}`
  end
end

local_paths = ['.']
gem_paths = Array(`bundle list --paths`.split("\n"))

Ctags
  .new
  .update(gem_paths + local_paths)
